### ISSUE TITLE
Helper 'map' does not work if I use turbolinks

### ISSUE THREAD

**Issue by bitimp** [axyjo/leaflet-rails#35]
If I use a helper 'map' - appears on the page space for maps, see the buttons, but nothing more. 

If I write the code for the event 'page:load', then everything works.

**Comment by elsurudo** [comment]
> If I write the code for the event 'page:load', then everything works.
What do you mean by this?

**Comment by elsurudo** [comment]
By the way, I just tested on the latest version, and the `map` helper is working with turbolinks. Only tested in latest Safari so far, so YMMV.

**Comment by axyjo** [comment]
Closing due to age. Please reopen if you're still having issues.
