### ISSUE TITLE
map helper does not work with default subdomains

### ISSUE THREAD

**Issue by tbk303** [axyjo/leaflet-rails#36]
Currently the map helper does not work if not custom subdomain configuration is used. Problem is, the subdomains config option is not deleted from the options has if it is nil, hence an empty string will be passed as subdomains to L.tileLayer

Something like this is required at the top of view_helper.rb:

```
subdomains = options.delete[:subdomains]
```

Workaround: Add the default subdomains to the leaflet initializer:

```
Leaflet.subdomains = 'abc'
```

**Comment by axyjo** [comment]
Closing due to age. Please reopen if you're still having issues.
