### ISSUE TITLE
ReferenceError: L is not defined

### ISSUE THREAD

**Issue by holisticode** [axyjo/leaflet-rails#38]
Hi, sorry for writing an issue for this, but I can't get any further...maybe it's really simple.

I followed your README, installed the leaflet-rails gem, added the "require" statements in application.css and application.js, added the leaflet.rb in initializers, and also added the depend_on_assets tags in application.css because I am using rails 4.1.4.
I created a map view, and the only content is the helper method:

<%= map(:center => {
  :latlng => [51.52238797921441, -0.08366235665359283],
    :zoom => 18
    }) %>

I always get "ReferenceError: L is not defined" in the browser...what could I be missing? In the browser inspection, I can see the leaflet.js being referenced as "/assets/leaflet.js" and that file exists there for that URL. Looking further, I can see that sprockets adds all javascript includes at the end of the file, but the helper generates a script before that in the middle of the page where the map div is....

Any suggestion?

**Comment by axyjo** [comment]
Closing due to age. Please reopen if you're still having issues.

**Comment by muzz00ka** [comment]
Hi all, 

I am having the same issue with 'ReferenceError: L is not defined'. I have followed the guide and have been trying to implement the map for the last 2 night now, with no avail. The only way I am able to get the map to work is if I add
 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"/>
< <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"/> 
into the head of HTML file I am trying to create. Which with my limited knowledge means the gem is not actually working.

I have checked the and I am Using leaflet-rails 1.6.0

I have added 'gem 'leaflet-rails'' to the Gemfile

I have added '*= require leaflet' to the application.css file

I have added '//= require' leaflet to the application.js file

I have added the code below to application.html.erb
```
 <%= javascript_pack_tag 'application', 'data-turbolinks-track': true %>
  <%= stylesheet_link_tag 'application' %>
```


I have added the code below to the leaflet.rb file I created
```
 ' Leaflet.tile_layer = 'http://{s}.tile.cloudmade.com/YOUR-CLOUDMADE-API-KEY/997/256/{z}/{x}/{y}.png'
# You can also use any other tile layer here if you don't want to use Cloudmade - see http://leafletjs.com/reference.html#tilelayer for more
Leaflet.attribution = 'Your attribution statement'
Leaflet.max_zoom = 18' 
```
When I refresh the page and inspect the HTML, the script is running the below code.

```
var map = L.map('map', {});
map.setView([51.52238797921441, -0.08366235665359283], 18);
L.tileLayer('http://{s}.tile.cloudmade.com/YOUR-CLOUDMADE-API-KEY/997/256/{z}/{x}/{y}.png', {
          attribution: 'Your attribution statement',
          maxZoom: 18,
}).addTo(map);
```

I am pretty lost on what to try next as I am very new to Rails.

I would highly appreciate any help. Regards, Rory.
