### ISSUE TITLE
Rails 4.2 following install guide, I get Sprockets::FileNotFound: couldn't find file 'leaflet'

### ISSUE THREAD

**Issue by 01010000101001100** [axyjo/leaflet-rails#43]
When I try to place "= require leaflet" to both - CSS and JS I am getting an error.

For CSS I am getting:
![screen shot 2015-04-13 at 2 39 09 pm](https://cloud.githubusercontent.com/assets/4720153/7110976/5dcb339e-e1ec-11e4-8d26-af524577cfc2.png)

Same error for JS in the console:
**Error: Sprockets::FileNotFound: couldn't find file 'leaflet'**

**Comment by axyjo** [comment]
Investigating.

**Comment by Ch4s3** [comment]
:+1:

**Comment by axyjo** [comment]
Closing due to age. Please reopen if you're still having issues.
