### ISSUE TITLE
Map option scrollWheelZoom doesn't work.

### ISSUE THREAD

**Issue by Julien-Nicault** [axyjo/leaflet-rails#46]
I defined my map this way:

<%= map(:container_id => "map-canvas",
:scrollWheelZoom => :false,
:center => {
  :latlng => [46.203, 6.142],
  :zoom => 14
},
:markers => @markerslist
) %>

but the code is rendered this way:

L.tileLayer('https://api.tiles.mapbox.com/v4/{...}/{z}/{x}/{y}.png?access_token={...}', {
          attribution: 'MapBox',
          maxZoom: 18,
scrollWheelZoom: 'false',
subdomains: '',
}).addTo(map)

If I remove the quotes around 'false', then the option is taken into account.

In lib/leaflet-rails/view_helpers.rb line 81, I see the quotes are added to each option.
How would it be possible to workaround this?

**Comment by Julien-Nicault** [comment]
In fact this should fail just the same with all boolean options

**Comment by soynog** [comment]
Is there any way to set boolean options (like scrollWheelZoom) in the map helper or initializer?

**Comment by axyjo** [comment]
Closing due to age. Please reopen if you're still having issues.
