### ISSUE TITLE
Error: No value provided for variable {s} with layers providers with a tile layer with {s}

### ISSUE THREAD

**Issue by persep** [axyjo/leaflet-rails#49]
Hi,
I have a working example on a page that displays a map with leaflet-rails 0.7.7 and rails 4.2.6
my stylesheets/application.css
`#map {
    height: 450px;
}`

my javascripts/application..js
`//= require jquery`
`//= require jquery_ujs`
`//= require turbolinks`
`//= require leaflet`
`//= require_tree .`

my views/routes/show.html.erb
`<%= map(:center => {
  :latlng => [51.52238797921441, -0.08366235665359283],
  :zoom => 12
}) %>`

my config/initializers/leaflet.rb:
`Leaflet.tile_layer = 'http://a.tile.openstreetmap.org/{z}/{x}/{y}.png'
Leaflet.attribution = 'Tiles courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a>'
Leaflet.max_zoom = 18`

As I say it works.
But when I change the `Leaflet.tile_layer` to the one that appears in the Leaflef examples, ie:
`Leaflet.tile_layer = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` I get the error and if I change it to `Leaflet.tile_layer = 'http://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png'` (also from the leaflets examples) I also get the same error.
How can i fix the reference to that s variable?

**Comment by persep** [comment]
Here is a [jsfiddle](https://jsfiddle.net/eydnazez/)

**Comment by axyjo** [comment]
Thanks for the report -- it seems like leaflet-rails overrides the default value when it should not. I will fix this sometime this week.

**Comment by persep** [comment]
In the jsfiddle from above if you delete
`subdomains: ' '`
from
`addTo(map);`
It works

**Comment by persep** [comment]
I've just seen that the version I have downloaded from rubygems is version 0.7.7 that has the subdomains empty list problem and I've tried with the github master branch wich is version "1.0.0-rc1"  and it doesn't have this problem.
Maybe updating the gem version in  rubygems is enought fix

**Comment by axyjo** [comment]
Closing due to age. Please reopen if you're still having issues.
