### ISSUE TITLE
fitbounds padding not working

### ISSUE THREAD

**Issue by laylacodogno** [axyjo/leaflet-rails#50]
Hello,
the fitbounds output are not considering the padding parameter.

I defined my map like this:

```
<%=
          map(:container_id => "mapid",
            :markers => markers,
            :fitbounds => bounds
          )
        %>
```

where bounds are my [] of latlng. it work very well like this but
I tried to use the padding parameter, and didn't work so we had to use em script tag after that

```
<!--script feito devido a falta de compatibilidade da gem para receber padding em fitbounds -->
      <script type="text/javascript">
        map.fitBounds(L.latLngBounds(<%= bounds %>), { padding: [50,50] });
      </script>
```

**Comment by axyjo** [comment]
Closing due to age. Please reopen if you're still having issues.
