### ISSUE TITLE
leaflet-routing-machine integration

### ISSUE THREAD

**Issue by ravishankarkm** [axyjo/leaflet-rails#51]
Hi,

How to integrate [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine) with leaflet-rails ?

Thanks.

**Comment by kirantpatil** [comment]
:100: :+1:

**Comment by axyjo** [comment]
The instructions on http://www.liedman.net/leaflet-routing-machine/ should work, once you add that asset to your project.
