### ISSUE TITLE
Marker icon URL detection doesn't play nice with asset digests

### ISSUE THREAD

**Issue by emilevictor** [axyjo/leaflet-rails#59]
I've run into a strange situation with leaflet-rails and its marker-icon.png asset that is bundled with the gem. In my app, I have included my own version of this file in my assets/images folder, which is ahead of the gem's version in Rails.application.config.assets.paths.

When I run this in production, I see the following:

http://beta.pitot.io/flights/2035

As you can hopefully see on the map, the marker appears in HTML as:

http://beta.pitot.io/assets/marker-icon-f8cd76868804022ae9aeb0e99417ccb0ced2db3a9b4e107ec44f4a43ee9a6635.png")marker-icon.png

Including the quote and the parentheses before marker-icon.png.

This doesn't appear in development without asset precompilation, and didn't previously occur before an update to the leaflet gem.

 I will give you a pull request with a modified version of the gem which works nicely with the digests. You might be able to come up with a nicer version, as mine is a monkeypatch.

**Comment by arael** [comment]
I have the same issue:

`<img src="http://localhost:3000/assets/marker-icon-574c3a5cca85f4114085b6841596d62f00d7c892c7b03f28cbfa301deb1dc437.png&quot;)marker-icon-2x.png" class="leaflet-marker-icon leaflet-zoom-animated leaflet-interactive" style="margin-left: -12px; margin-top: -41px; width: 25px; height: 41px; transform: translate3d(890px, 298px, 0px); z-index: 298; outline: medium none;" tabindex="0">`

**Comment by kaveh-ahmadian-sp** [comment]
There seems to be a fix committed after the 1.0.2 release:
https://github.com/axyjo/leaflet-rails/commit/09451b92ceee23cf040268e83958858cdcf62f4a

Until a new version is released, you'll need to add the following lines of JS to your app:
L.Marker = L.Marker.extend({
  options: {
    icon: new L.Icon.Default()
  }
});

**Comment by axyjo** [comment]
Released a new version.
