### ISSUE TITLE
Can't create initializer

### ISSUE THREAD

**Issue by rbUUbr** [axyjo/leaflet-rails#68]
Hi! With help of your guide, i just added leatflet-rails gem to my Gemfile, and than tried to create initializer for this gem(just ```touch config/initializers/leatflet.rb```), tried to put this strings into it
```
Leaflet.tile_layer = "http://{s}.tile.cloudmade.com/YOUR-CLOUDMADE-API-KEY/997/256/{z}/{x}/{y}.png"
# You can also use any other tile layer here if you don't want to use Cloudmade - see http://leafletjs.com/reference.html#tilelayer for more
Leaflet.attribution = "Your attribution statement"
Leaflet.max_zoom = 18
```
But when i started my server, i got an exception from this file:
``` Uninitialized constant Leatflet ```
Will be glad if you will answer fast!
Rails v.: 5.1.0

**Comment by axyjo** [comment]
`Leatflet` -> Did you mean to type `Leaflet` instead?

**Comment by axyjo** [comment]
No updates in a while -- feel free to reopen if you're still having trouble.
