### ISSUE TITLE
Support For MarkerClusters

### ISSUE THREAD

**Issue by asecondwill** [axyjo/leaflet-rails#74]
Currently I can't add marker clusters if I add the map and markers using the helper.  Would be good to have a way to do that.

**Comment by axyjo** [comment]
Hi!

The helpers are great for getting started, but for any serious work, I'd recommend just using a Javascript file, which'll let you use the marker clusters plugin as intended. Let me know if that helps!

**Comment by asecondwill** [comment]
ok, thanks
