### ISSUE TITLE
Leaflet 1.2 released August 9, 2017

### ISSUE THREAD

**Issue by MtnBiker** [axyjo/leaflet-rails#75]
"The major reason for this release is to address an unfortunate regression in the 1.1.0 release, causing trouble with several plugins. Traditionally, Leaflet plugins has altered and added to Leaflet’s namespace (the L global), something which is no longer allowed after Leaflet was rebuilt on ES6 modules (an imported module is read-only). To preserve backwards compatibility, we have made a workaround to make the Leaflet namespace and its contents mutable again."

**Comment by axyjo** [comment]
Released
