### ISSUE TITLE
Cannot read property 'trim' of undefined. at Object.trim (Util.js:124) at Object.splitWords

### ISSUE THREAD

**Issue by sergiy17** [axyjo/leaflet-rails#78]
When searching for the **Util.js:124** as is in error - I am finding the 
```
trim: function (str) {
		return str.trim ? str.trim() : str.replace(/^\s+|\s+$/g, '');
	}
```
method, with the undefined **str**.
End the trim method is defined here:
https://github.com/axyjo/leaflet-rails/blob/40f51280d73bde57bb04fc881aacc88ce63108b5/vendor/assets/javascripts/leaflet-src.js.erb#L135
Did somebody have the same issue?

![screenshot from 2017-11-27 22-47-28](https://user-images.githubusercontent.com/12006123/33288438-f89da1be-d3c4-11e7-9b8d-42c3563bfca2.png)

Did somebody have the same issue?

**Comment by axyjo** [comment]
This method hasn't been changed from upstream. I'd recommend asking over at https://github.com/Leaflet/Leaflet
