### ISSUE TITLE
Better changelog or releases/tags

### ISSUE THREAD

**Issue by chevinbrown** [axyjo/leaflet-rails#79]
We're upgrading from 0.7 to 1.2 and it's _very_ difficult to understand what has changed without looking directly at commits. Please help the OSS world by either updating the changelog or having helpful notes attached to tags/releases.

**Comment by axyjo** [comment]
Hi @chevinbrown,

Releases track upstream version numbers, so you can check out the changelog at https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md, or release notes at: https://github.com/Leaflet/Leaflet/releases

**Comment by chevinbrown** [comment]
I think my comment still stands, but I accept.
