### ISSUE TITLE
Compatibility with Webpacker and Rails 6

### ISSUE THREAD

**Issue by elipinska** [axyjo/leaflet-rails#93]
Hi there,

Just wondering if there are any plans to make this gem compatible with Rails 6 and the new way of compiling Javascript using Webpacker?

**Comment by axyjo** [comment]
@elipinska Could you elaborate a bit more on what kind of support you'd expect from the gem? I haven't used Rails 6 but with Webpacker, you should be able to use the `leaflet` package directly with something like `yarn add leaflet`.

**Comment by markmcdonald51** [comment]
Love this gem but I too am using Rails6 and finding it really hard to get this working correctly. Not sure if it's a problem with the way webpacker arranges files when compiling or what... 

At best I have been able to render a map with the tiles all out of order which tells me that the leaflet.css is not being included. However, when I add it in by directly linking it to a source or even pasting into the page (just to see if I can get it to work) everything disappears. 
Anyway, thanks for maintaining this gem. I really like the OSM over gmaps for sure. Just totally frustrating trying to get this to work now.

**Comment by markmcdonald51** [comment]
Nevermind.... it was just a matter of getting the right paths to the css files and overriding a little bug in the leaflet lib to override the marker icons!

Thx!

require('leaflet/dist/leaflet.css')
         
import L from 'leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png'),
});

**Comment by axyjo** [comment]
Marking as resolved!

**Comment by fwolfst** [comment]
I would still love to see this reflected in the README. I am all sprockets (rails5), too but on the other hand I'd like to fiddle with the new tech.

**Comment by axyjo** [comment]
@fwolfst mind opening a pull request? I'm not entirely clear what you'd like documented.

**Comment by fwolfst** [comment]
> @fwolfst mind opening a pull request? I'm not entirely clear what you'd like documented.

I tried with a stock Rails6 app and this doesnt seem to work. The reason likely is that the javascript inclusion now works with webpacker (by default). Adding it by hand (`yarn add leaflet`) is straight forward, but I was hoping for a solution outside of that ecosystem.

**Comment by axyjo** [comment]
@fwolfst okay, so just to confirm I got that right: you'd like to use `leaflet-rails` with Rails 6, but outside of the Webpacker infrastructure that's already set up?

**Comment by fwolfst** [comment]
> @fwolfst okay, so just to confirm I got that right: you'd like to use `leaflet-rails` with Rails 6, but outside of the Webpacker infrastructure that's already set up?

Yes.

**Comment by thomaswitt** [comment]
Any updates here? Still trying gonget it up and running with Rails 6 and Webpack without Sprockets.

**Comment by axyjo** [comment]
I haven't had a chance to take a look and investigate as I'm currently not using Rails 6 for any of my projects.

**Comment by thomaswitt** [comment]
Here is a working solution for Rails 6: https://github.com/Leaflet/Leaflet/issues/6837#issuecomment-822251450
