### ISSUE TITLE
Dropping `git` in gemspec & using Packaging extension

### ISSUE THREAD

**Issue by utkarsh2102** [axyjo/leaflet-rails#95]
Hi @axyjo,

Thanks for your great work!
However, whilst maintaining this in Debian, I found some issues that could be fixed by the `Packaging` extension of RuboCop. Would you be interested in doing so?

One specific issue that I'd like to resolve is dropping `git` in the gemspec file.
I'll be happy to raise a PR if you concur with this :)

**Comment by axyjo** [comment]
Thanks for the suggestion!

**Comment by utkarsh2102** [comment]
This is great, thanks!
Would you be open to using RuboCop as well?
